language: java

jdk:
  - openjdk8

# Prevent Travis from running automatic project install.
install:
  - true

script:
  - ./gradlew build

before_cache:
  - rm -f "$HOME"/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
